# Generated by Django 6.0.4 on 2026-04-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_report_doctor_alter_report_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
